### ISSUE TITLE
Accelerate the model inference of GLM-10B

### ISSUE THREAD

**Issue by Ant0082** [THUDM/GLM#47]
Hi, I want to accelerate the model inference of GLM-10B, do you have any suggestion? Or have some attempts.

**Comment by duzx16** [comment]
You can use FasterTransformer (https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md). Our model architecture is close to Megatron-LM.
We already accelerated the GLM-130B with FasterTransformer (https://github.com/THUDM/GLM-130B/blob/main/docs/inference-with-fastertransformer.md). However, the implementation cannot be directly applied on GLM-10B since the model architecture is slightly different.

**Comment by un-certainty** [comment]
Hi @duzx16 ,

Could you point out the implementation differences between GLM-130B and GLM-10B-Chinese? I find some in the papers, but the list may be incomplete:

| Component | GLM-130B | GLM-10B-Chinese |
| --- | --- | --- |
| LayerNorm | DeepNorm |  rearrange the order of layer normalization and the residual connection |
| PositionEmbedding | RoPE | 2D positional encodings |

Also, it seems complicated to [accelerate GLM-130B with FasterTransformer](https://github.com/NVIDIA/FasterTransformer/compare/main...THUDM:FasterTransformer:main), which requires writing CUDA kernels. Do you have any plan to provide an official implementation of GLM-10B-Chinese? Or do you have any suggestion on how to adjust the code for the 10B model?

Also, there are plenty of other options, such as DeepSpeed MII. Which solution do you think is best suite for accelerating GLM-10B?

**Comment by un-certainty** [comment]
@duzx16 Any suggestion?

**Comment by ppppppppig** [comment]
大佬@duzx16，请问@un-certainty总结的区别是否完整呢，我这边总结的区别也与之类似呢。

另外，对于“rearrange the order of layer normalization and the residual connection”，论文中没有提到调整为什么顺序，我简单看了下glm代码，冒似会在进入注意力模块前添加一个归一化操作，请问这样理解是否正确

辛苦大佬解答下
