### ISSUE TITLE
Questions about 10B-chinese

### ISSUE THREAD

**Issue by mx8435** [THUDM/GLM#81]
Hi, 
    I've tested `GLM-10B-chinese` pretraining in our cluster 256 x A100 (80G) with RDMA using `config/ds_block_10B_chinese.sh` and `config/config_block_10B.json` which choose stage 2 in ZeRO. The train batch size is 256\*21=5376. However, the speed is too slow: each step cost __38s__, and if we train 150k steps as script `config/ds_block_10B_chinese.sh`, it will cost __65__ days to train 150k steps(stage 1 with 512 seq_len).  I've the following questions:
    1. Is MP_SIZE=1 when pretraining 10B-chinese ?
    2. Is the 10B-chinese model released pretrained using batch_size=256\*21=5376, train_steps=150k and zero stage 2 as `config/config_block_10B.json`?
    3.  Why use two stages to pretrain `10B-chinese` (first train 150k steps with seq_len=512 and batch_size=256\*21, second train 150k steps with seq_len=1024 and batch_size=256\*8) ?
    4.  What is a step elapsed in your previous pretraining `10B-chinese`, and how many hours the pretraining __each__ stage cost ?

**Comment by duzx16** [comment]
1. Yes. Practically we found that using ZeRO optimizer is faster than model parallelism when possible.
2 & 3: the 10B-chinese model is pretrained with two stages. The first stage uses `config/ds_block_10B_chinese.sh` with 72k steps and the second stages uses `config/ds_block_10B_chinese_longer.sh` with 8k steps. The reason is that the time complexity increases with the square of the sequence length. Training with shorter sequence length can 
4. Each step costs about 15s in the first stage and about 53s in the second stage.

**Comment by mx8435** [comment]
@duzx16 
Thanks for your reply. 
1. Is the global_batch_size in Stage 1 256\*21=5376 and 256\*8=2048 in Stage 2 ?
2. The ds_config used in pretrain is `config/config_block_10B.json` ?
